#ifndef DATAKIT_CONFIG_H
#define DATAKIT_CONFIG_H

#include <QtCore/qglobal.h>

#define DATAKIT_VERSION_MAJOR 1
#define DATAKIT_VERSION_MINOR 0
#define DATAKIT_VERSION_PATCH 0
#define DATAKIT_VERSION_STR   "1.0.0"
#define DATAKIT_VERSION       DATAKIT_VERSION_CHECK(DATAKIT_VERSION_MAJOR, DATAKIT_VERSION_MINOR, DATAKIT_VERSION_PATCH)
#define DATAKIT_VERSION_CHECK QT_VERSION_CHECK

#endif // DATAKIT_CONFIG_H
